name = "TheArtOfComputerProgramming"
uuid = "a2d8b244-25fa-45bb-8385-903e6ebb3f12"
authors = ["Thomas Poulsen <ta.poulsen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
